# Hekun Blog
# 2020-9-22
# Site settings
title: Hekun Sam
email: 3320382157@qq.com
description: > # this means to ignore newlines until "baseurl:"
  Called Me "KunGe".
baseurl: "" # the subpath of your site, e.g. /blog
lang: "en"
url: "http://yalisandsoso.github.io" # the base hostname & protocol for your site
twitter_username: yuhekun
github_username:  yalisandsoso
disqus_username:

# Build settings
markdown: kramdown
permalink: /:categories/:title/

# Posts settings
future: true
safe: false
lsi: false
excerpt_separator: "\n\n"

# Theme settings
compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all


sass:
  sass_dir: assets/_sass
  style: compressed


images: '/assets/images'
